modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "livelierpokemon"
version = "${version}"
displayName = "LivelierPokemon"
authors = "NecroSo1"
description = "Integrates Pokemon and Pokemon abilities into Minecraft!"

[[dependencies.livelierpokemon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.livelierpokemon]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.214,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.livelierpokemon]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "livelierpokemon-common.mixins.json"